<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	
		<ApplicationIcon>Assets\ADComputerSearchTool.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Assets\ADComputerSearchTool.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.105.0" />

		<PackageReference Include="System.DirectoryServices.Protocols" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Assets\ADComputerSearchTool.ico">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>

</Project>